In [246]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [247]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [248]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [249]:
MATRIX = torch.tensor([[3,4],[23,4]])

In [250]:
MATRIX.shape

torch.Size([2, 2])

In [251]:
# TENSOR
TENSOR= torch.tensor([[[3,4,3],
                       [43,44,4],
                       [4,4,77]]])

In [252]:
TENSOR.ndim

3

In [253]:
TENSOR.shape

torch.Size([1, 3, 3])

In [254]:
TENSOR[0][1][0]

tensor(43)

In [255]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(2,3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.8179, 0.8384, 0.5706, 0.6433],
          [0.6788, 0.8175, 0.1951, 0.8502],
          [0.1609, 0.9915, 0.0547, 0.5230]],
 
         [[0.6794, 0.9772, 0.5976, 0.3062],
          [0.2735, 0.8353, 0.3890, 0.0048],
          [0.1363, 0.5581, 0.7351, 0.0402]]]), torch.float32)

In [256]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros,zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [257]:
# tensor with all ones
ones = torch.ones(size=(2,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [258]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
# one tensor of a certain type with the same shape as another tensor ,creating tensor with all zer0s like zer_to_ten
zero_like = torch.zeros_like(input = zero_to_ten)
zero_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [260]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device= None,
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [261]:
###  Getting Info from Tenors
# Create a tensor
tensor_t = torch.rand(3, 4)

# Find out details about it
print(tensor_t)
print(f"Shape of tensor: {tensor_t.shape}")
print(f"Datatype of tensor: {tensor_t.dtype}")
print(f"Device tensor is stored on: {tensor_t.device}") # will default to CPU

tensor([[0.4377, 0.4549, 0.6179, 0.4037],
        [0.5427, 0.0680, 0.1923, 0.8299],
        [0.4472, 0.6599, 0.5592, 0.4235]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [262]:
# operations on tensor
# Substraction,Division,Matrix multiplication
# Addition ,Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [263]:
# Multiply it by 10
tensor * 10

# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [264]:
# Subtract and reassign
tensor = tensor - 10
tensor


tensor([-9, -8, -7])

In [265]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [266]:
# Can also use torch functions
torch.mul(tensor, 10)
torch.add(tensor,10)


tensor([11, 12, 13])

In [267]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [268]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [269]:
  # Matrix Multiplication with another matrix
torch.matmul(tensor,tensor)

tensor(14)

In [270]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [271]:
# getting the time of multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 62 µs, sys: 6 µs, total: 68 µs
Wall time: 72.2 µs


tensor(14)

In [272]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [273]:
# View tensor_A and tensor_B
print(tensor_A.shape,tensor_B.shape)


torch.Size([3, 2]) torch.Size([3, 2])


In [274]:
# to fix the matrix mult shape issues we can ttranspose the matrix and then multiply (inner dimensions must match for matrix multiplication)
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_A.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [276]:
# torch.mm is a shortcut for matmul
new_tensor= torch.mm(tensor_A, tensor_B.T)
print(new_tensor)
print ("shape=",new_tensor.shape)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
shape= torch.Size([3, 3])


In [275]:
# Create a tensor
x = torch.arange(0, 10, 1)
x
print("minimum : ",x.min())
print("maximum : ",x.max())
print("mean : ", x.type(torch.float32).mean() )
print("sum : " ,torch.sum(x));

minimum :  tensor(0)
maximum :  tensor(9)
mean :  tensor(4.5000)
sum :  tensor(45)


In [277]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [278]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype
tensor_int8= tensor.type(torch.int8) 
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [283]:
# reshaping
# Create a tensor
import torch
x = torch.arange(0., 12.)
x, x.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]))

In [284]:
x_reshaped = x.reshape(6,2)
x_reshaped, x_reshaped.shape

(tensor([[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]), torch.Size([6, 2]))

In [286]:
z = x.view(4, 3)
z, z.shape

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]), torch.Size([4, 3]))

In [285]:
# Changing z changes x in tensor.view
z[:, 0] = 5
z, x

(tensor([[ 5.,  1.,  2.],
         [ 5.,  4.,  5.],
         [ 5.,  7.,  8.],
         [ 5., 10., 11.]]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [287]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.]])

In [288]:
# torch.squeeze

x = torch.zeros(2, 1, 2, 1, 2)
y = torch.squeeze(x,1)
y2= torch.squeeze(x)
y.shape, y2.shape

(torch.Size([2, 2, 1, 2]), torch.Size([2, 2, 2]))

In [289]:
# torch.insqueeze
y_unsqueeze= torch.unsqueeze(y, 1)
y_unsqueeze.shape

torch.Size([2, 1, 2, 1, 2])

In [290]:
# Indexing (selecting data from tensors)

# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [291]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [292]:
# Let's index bracket by bracket

print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [293]:
# PyTorch tensors & NumPy
# numpy array --> pytorch tensors
import numpy as np
import torch
x= np.arange(0,8)
torch = torch.from_numpy(x)
x,torch

(array([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 4, 5, 6, 7]))

In [294]:
# Change the array, keep the tensor
# does not change the tensor , .from_numpy creates separate memory tensor 
x = x + 1
x, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [305]:
# tensor --> numpy
import numpy as np
import torch
tensor= torch.ones(size=(3,5))
tensor.shape
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32))

In [307]:
numpy_tensor.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [311]:
# Change the tensor, keep the array the same
# does not change the tensor , .from_numpy creates separate memory tensor 
tensor = tensor + 1
tensor, numpy_tensor


(tensor([[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32))

In [315]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8960, 0.8157, 0.0207, 0.4629],
        [0.4184, 0.8656, 0.2020, 0.3566],
        [0.6307, 0.9170, 0.6129, 0.9230]])

Tensor B:
tensor([[0.2690, 0.1533, 0.9008, 0.1659],
        [0.7549, 0.2523, 0.5031, 0.3915],
        [0.8202, 0.2046, 0.0570, 0.0209]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [323]:
import torch

RANDOM_SEED= 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C= torch.rand(3,4)

# setting after each rand
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D= torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_C}\n")
print(f"Tensor B:\n{random_tensor_D}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_C == random_tensor_D


Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])